### PR TITLE
Removed smslibrary submodule and added placeholder network module

### PR DESCRIPTION
**Pull request by CremaLuca**
I wanted to remove the submodule to switch to Jitpack library, which is downloaded when you checkout the repository and you don't have to `git submodule update --remote --checkout`.
Had to add a module in order to add the `implementation` and keep the reference for future implementations of this library.

### CODE REVIEW

**Review by Cogno-Marco — COMMENTED** [review]
Have you correctly removed the gitmodule? Don't you also have to delete another file with the commit hash?

**Comment by CremaLuca** [comment]
Nope, I'm 100% sure the submodule has been removed, the hash of the commit was in .gitmodules and it has been deleted

**Comment by CremaLuca** [comment]
Yes, i'm 100% sure the submodule has been correctly removed

**Review by Cogno-Marco — APPROVED** [review]
Let's integrate this 👍

**Pull request merged**
